version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    command: ["python", "main.py"]
    restart: always
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    container_name: dtb_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tg_bot
    ports:
      - "20000:5432"

volumes:
  postgres_data:
